import liuxiaoyang from '../assets/images/liuxiaoyang.jpeg';
import daizhen from '../assets/images/daizhen.jpg';
import pengxi from '../assets/images/pengxi.jpg';
import zhengxiaoguang from '../assets/images/zhengxiaoguang.jpg';

const items = [
  {
    name: '王昊奋',
    role: 'openbase发起人',
    position: 'CTO',
    organization: '深圳狗尾草智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_01.png',
  },
  {
    name: '谢殿侠',
    role: 'openbase发起人',
    position: 'CEO',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_02.png',
  },
  {
    name: '丁力',
    role: 'openbase发起人，cnSchema作者',
    position: 'CTO',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_08.jpg',
  },
  {
    name: '陈华钧',
    role: 'openbase发起人',
    position: '教授',
    organization: '浙江大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_31.jpg',
  },
  {
    name: '崔宝秋',
    role: 'openbase发起人',
    position: '小米科技首席架构师、人工智能与云平台副总裁',
    organization: '北京小米智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_26.jpg',
  },
  {
    name: '顾进广',
    role: '众包框架总体设计与工作协调',
    position: '教授',
    organization: '武汉科技大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_24.jpg',
  },
  {
    name: '漆桂林',
    role: 'openbase发起人',
    position: '教授',
    organization: '东南大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_03.png',
  },
  {
    name: '李涓子',
    role: 'openbase发起人',
    position: '博士，教授',
    organization: '清华大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_17.jpg',
  },
  {
    name: '刘作鹏',
    role: 'openbase发起人',
    position: '智能问答技术总监',
    organization: '北京小米智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_28.jpg',
  },
  {
    name: '王宇',
    role: 'openbase发起人',
    position: 'COO',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_13.jpg',
  },
  {
    name: '高峰',
    role: '众包平台总体设计和开发',
    position: '讲师',
    organization: '武汉科技大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_25.jpg',
  },
  {
    name: '孟遥',
    role: '研究专家',
    position: '为知识图谱提供可视化工具，分析和展示知识图谱',
    organization: '富士通研究开发中心有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_06.jpg',
  },
  {
    name: '张鹏',
    role: 'kg4ai知识图谱构建',
    position: '高级工程师',
    organization: '清华大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_19.jpg',
  },
  {
    name: '尚忆秋',
    role: 'openbase众包产品设计',
    position: '产品经理',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_11.jpg',
  },
  {
    name: '高博',
    role: 'kg4ai数据支持',
    position: '高级工程师',
    organization: '清华大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_16.jpg',
  },
  {
    name: '吴天星',
    role: '百科知识图谱构建方法设计与开发',
    position: '算法工程师',
    organization: '东南大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_05.jpg',
  },
  {
    name: '唐杰',
    role: 'AMiner创始人、数据支持',
    position: '博士，副教授',
    organization: '清华大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_18.jpg',
  },
  {
    name: '吴杨',
    role: 'openbase众包前端开发',
    position: '研究生',
    organization: '浙江大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_33.jpg',
  },
  {
    name: '熊辉',
    role: 'openbase众包后端开发',
    position: '研究生',
    organization: '武汉科技大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_23.jpg',
  },
  {
    name: '李泰',
    role: '数据工具与算法研发',
    position: '知识图谱工程师lead',
    organization: '北京小米智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_27.jpg',
  },
  {
    name: '张伟',
    role: 'kg4ai数据处理',
    position: '助工',
    organization: '清华大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_20.jpg',
  },
  {
    name: '李丞',
    role: '百科知识图谱构建方法设计与开发',
    position: '算法工程师',
    organization: '东南大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_04.jpg',
  },
  {
    name: '姚光涛',
    role: 'openbase众包后端开发',
    position: '研究生',
    organization: '武汉科技大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_21.jpg',
  },
  {
    name: '李娟',
    role: 'openbase众包前后端开发',
    position: '研究生',
    organization: '浙江大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_32.jpg',
  },
  {
    name: '孙时',
    role: '前端开发',
    position: '智能问答系统开发',
    organization: '北京小米智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_29.jpg',
  },
  {
    name: '杨帆玉',
    role: 'openbase众包后端开发',
    position: '研究生',
    organization: '武汉科技大学',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_22.jpg',
  },
  {
    name: '王献敏',
    role: '产品经理',
    position: '知识图谱产品经理',
    organization: '北京小米智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_30.jpg',
  },
  {
    name: '李轩',
    role: 'openbase众包产品设计',
    position: '产品经理',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_09.jpg',
  },
  {
    name: '朱慧源',
    role: 'openbase网站UI设计',
    position: 'UI设计师',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_15.jpg',
  },
  {
    name: '杨帆',
    role: 'openbase网站UI设计',
    position: 'UI设计师',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_14.jpg',
  },
  {
    name: '孙胜男',
    role: '项目管理',
    position: '项目经理',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_12.jpg',
  },
  {
    name: '刘宜乐',
    role: '知识图谱产品经理',
    position: '知识图谱产品经理',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_10.jpg',
  },
  {
    name: '陈阳',
    role: '项目助理',
    position: '项目助理',
    organization: '北京海知智能科技有限公司',
    headpic: 'https://qiniu.ruyi.ai/vol_pic_07.jpg',
  },
  {
    name: '戴振',
    role: '工程师',
    organization: '小米科技武汉有限公司',
    position: '知识图谱工程师',
    headpic: daizhen,
  },
  {
    name: '彭茜',
    role: '产品经理',
    organization: '小米科技武汉有限公司',
    position: '知识图谱产品经理',
    headpic: pengxi,
  },
  {
    name: '郑小光',
    role: '前端工程师',
    organization: '小米科技武汉有限公司',
    position: '前端工程师',
    headpic: zhengxiaoguang,
  },
  {
    name: '刘潇洋',
    role: '前端工程师',
    organization: '小米科技武汉有限公司',
    position: '前端工程师',
    headpic: liuxiaoyang,
  },
];
export default items;
